# Generated by Django 6.0.1 on 2026-01-23 00:52

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=20, unique=True, verbose_name='닉네임')),
                ('img_profile', models.ImageField(blank=True, null=True, upload_to='profile/', verbose_name='프로필 이미지')),
                ('best_profit_rate', models.FloatField(default=0.0, verbose_name='최고 수익률')),
                ('total_games', models.IntegerField(default=0, verbose_name='총 플레이 횟수')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_capital', models.BigIntegerField(default=10000, verbose_name='현재 자본금(만원)')),
                ('remaining_chances', models.IntegerField(default=5, verbose_name='남은 기회')),
                ('is_finished', models.BooleanField(default=False, verbose_name='종료 여부')),
                ('final_profit_rate', models.FloatField(blank=True, null=True, verbose_name='최종 수익률(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_sessions', to=settings.AUTH_USER_MODEL, verbose_name='플레이어')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=20, verbose_name='캐릭터 이름')),
                ('idea_title', models.CharField(max_length=100, verbose_name='아이디어 제목')),
                ('idea_description', models.TextField(blank=True, verbose_name='아이디어 설명')),
                ('invest_amount', models.BigIntegerField(verbose_name='투자 금액(만원)')),
                ('is_success', models.BooleanField(verbose_name='성공 여부')),
                ('profit_rate', models.IntegerField(default=0, verbose_name='수익률(%)')),
                ('result_system_msg', models.TextField(blank=True, verbose_name='[SYSTEM] 메시지')),
                ('result_character_reaction', models.TextField(blank=True, verbose_name='[캐릭터] 반응')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='투자 시간')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='game.gamesession', verbose_name='게임 세션')),
            ],
        ),
    ]
