# Generated by Django 6.0.1 on 2026-01-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamesession",
            name="remaining_reroles",
            field=models.IntegerField(default=5, verbose_name="남은 패스 횟수"),
        ),
    ]
